### ISSUE TITLE
Issue when saving it with bower install --save betsol-ng-intl-tel-input

### ISSUE THREAD

**Issue by sultanrbt** [betsol/ng-intl-tel-input#7]
I have installed plugin by cloning it from git [Jacknor](https://github.com/jackocnr/intl-tel-input#getting-started)

after that i was installing it with "bower install --save betsol-ng-intl-tel-input" i am getting error as "prefix the choice with ! to persist it to bower.json"

attached a screen shot any ideas?
![issue](https://cloud.githubusercontent.com/assets/17764295/13695138/b6b7b6a8-e781-11e5-8ad6-1c542650ab5a.png)

**Comment by jordandotme** [comment]
I'm not sure why the author of this repo tells users to install the original plugin when they have it as a dependency anyway. 

The following [bower.json](https://github.com/betsol/ng-intl-tel-input/blob/master/bower.json) currently requires version 8.4.6 and above.  If you are wanting to use this angular directive, then go with option 2. It's best to use the version intended. 

When you prefix with !, it will save you having to choose the option again whenever you reinstall your own bower dependencies (Be careful you choose the right version when doing this, as it will persist it to your bower.json, like it says).

**Comment by sultanrbt** [comment]
@bestol(author) can you please update it without dependencies as the way [hodgepodgers](https://github.com/hodgepodgers/ng-intl-tel-input/issues) is doing so that we can install directly without any dependencies.

**Comment by jordandotme** [comment]
@sultanrbt: That's not a reasonable feature to request. It's actually better that the module specifies it's own dependencies, as this prevents issues later on when users have conflicting versions that don't work with any new code introduced. 

If you want to install your own version, then you can do so, but don't use bower. I have proposed changes in the following PR #8 to help make it clearer for you and others.

**Comment by slavafomin** [comment]
Hello there!

The module should explicitly define all of it's dependencies (i.e. `angular` and `intl-tel-input` in this case), that what dependencies are for. I'm going to define all of the required dependencies using the minimum stability version possible, i.e. for `angular` it's `^1.2` (tested) right now.

@sultanrbt , your conflict was due to the fact, that you were using two different modules that require different versions of the `intl-tel-input`. This is the normal and expected behavior. However, you should either use module from @hodgepodgers, or from us. It doesn't make sense to use both.

If you have any further questions/propositions, I will be glad to discuss them. Cheers!
